openapi: 3.0.2

info:
  title: e_upgrade API Documentation
  description: API documentation for e_upgrade
  version: '1.0'

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /categories:
    get:
      tags:
        - Categories
      summary: Get all categories
      operationId: getAllCategories
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Categories'
          examples:
            ExampleCategories:
              value:
                - id: 1
                  name: Electronics
                - id: 2
                  name: Clothing

    post:
      tags:
        - Categories
      summary: Add a new category
      operationId: addCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Categories'
      responses:
        '200':
          description: Category added successfully

  /categories/{id}:
    get:
      tags:
        - Categories
      summary: Get category by ID
      operationId: getCategoryById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the category
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categories'
          examples:
            ExampleCategory:
              value:
                id: 1
                name: Electronics
        '404':
          description: Category not found

    put:
      tags:
        - Categories
      summary: Update a category
      operationId: updateCategory
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the category to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Categories'
      responses:
        '200':
          description: Category updated successfully
        '404':
          description: Category not found

    delete:
      tags:
        - Categories
      summary: Delete a category
      operationId: deleteCategoryById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the category to delete
      responses:
        '200':
          description: Category deleted successfully
        '404':
          description: Category not found

  /order_details:
    get:
      tags:
        - Order_details
      summary: Get all order details
      operationId: getAllOrder_details
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order_details'

    post:
      tags:
        - Order_details
      summary: Add a new order detail
      operationId: addOrder_details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order_details'
      responses:
        '200':
          description: Order detail added successfully

  /order_details/{id}:
    get:
      tags:
        - Order_details
      summary: Get order detail by ID
      operationId: getOrder_detailsById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the order detail
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order_details'
        '404':
          description: Order detail not found

    delete:
      tags:
        - Order_details
      summary: Delete an order detail
      operationId: deleteOrder_detailsById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the order detail to delete
      responses:
        '200':
          description: Order detail deleted successfully
        '404':
          description: Order detail not found

    put:
      tags:
        - Order_details
      summary: Update an order detail
      operationId: updateOrder_details
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the order detail to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order_details'
      responses:
        '200':
          description: Order detail updated successfully
        '404':
          description: Order detail not found

components:
  schemas:
    Categories:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      example:
        id: 1
        name: Electronics

    Order_details:
      type: object
      properties:
        id:
          type: integer
        order_id:
          type: integer
        product_id:
          type: integer
        quantity:
          type: integer
        unit_price:
          type: number
      example:
        id: 1
        order_id: 123
        product_id: 456
        quantity: 3
        unit_price: 29.99
